[sweep_configuration]
method = "random"

[sweep_configuration.metric]
goal = "minimize"
name = "epoch_loss"

[sweep_configuration.parameters.batch_size]
values = [16]

[sweep_configuration.parameters.num_epochs]
values = [50]

[sweep_configuration.parameters.optimizer.parameters]
lr = { min = 0.001, max = 0.1 }
momentum = { min = 0.0, max = 0.9 }
dampening = { min = 0.0, max = 0.9 }
weight_decay = { min = 0.0, max = 0.3 }

[sweep_configuration.parameters.scheduler.parameters]
step_size = { values = [10] }

[sweep_configuration.parameters.aux_lambda]
min = 0.0
max = 0.4
